# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

sudo: false
language: python
matrix:
  include:
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.0.0.deb && sudo service elasticsearch restart
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
  - pip install codecov pytest pytest-cov
  # ^  DEPRECATION WARNING:
  # The automatic creation of a `requirements.txt` file is deprecated.
  # See `Dependency Management` in the docs for other options.
before_script:
  - git config --global user.email "cquiros@qlands.com"
  - git config --global user.name "Carlos Quiros"
script:
  - python setup.py develop
  - pytest --cov=./
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
  - if [[ "$COVERAGE" == "true" ]]; then codecov -e CODECOV_ENV || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
